function ADVR.onLoad()
    pickup.name = "BELL"
    pickup.desc = "Gain coins when you succesfully evade a hit"
    pickup.weight = 85
    pickup.maxAmount = 1
    pickup.amountUses = -1
    pickup.price = 35
    pickup.tier = 2
    pickup.spawnsIn = {relicPool.GOLDEN_CHEST}
    pickup.supportedInMultiplayer = true
end

function ADVR.onPickup()
    pickup.RegisterItem()
end

function ADVR.onPlayerEvade()
    player.currentCash = player.currentCash + 9
end
-- BELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELLBELL