function ADVR.onLoad()
    pickup.name = "Fortune Candle"
    pickup.desc = "After each floor recieve a fortune and some cash"
    pickup.weight = 75
    pickup.maxAmount = 1
    pickup.amountUses = -1
    pickup.price = 20
    pickup.tier = 3
    pickup.spawnsIn = { relicPool.SPECIAL, relicPool.BOSS }
    pickup.supportedInMultiplayer = true
end

function ADVR.onPickup()
    pickup.RegisterItem()
   player.currentCash = player.currentCash + 15
end



function ADVR.onAfterBossAreaGenerated(worldGenerator)
    SplashText()
    player.currentCash = player.currentCash + 5
end


Quotes = {
    "ey ill Shoot you - Jonathan",
    "hey you are playing relics galore, thats pretty cool",
    "Don't go surfing in South Dakota for a while",
    "Small things make base men proud. - William Shakespeare",
    "So you're back... about time...",
    "This place is pretty old, seems like some kind of ancient dungeon - ADVR movie",
    "Also try Augements+",
    "Ban monkey movement",
    "You have fih resprites installed...Right?",
    "67",
    "Blame Erthu",
    "Good news.  Ten weeks from Friday will be a pretty good day.",
    "Try out some NG+ on this next run",
    "If he is invincible, then how can I see him?",
    "Are you sure?",
    "You shall do as an appetizer",
    "In rust we don't trust",
    "This quote is not of the night - DuD",
    "Blame Jon",
    "Never blame Kuiq",
    "Blame Thom",
    "Why do we drive on a parkway, but park on a driveway",
    "Its not about the heart in the dog, its about the dog in the heart",
    "Also try Darkest Decent",
    "Also try Cgniks Dungeon",
    --get out of my code nerd.
    "Blame Sebwr",
    "Also try beyond 3.15",
    "Also try Specialty challenge Pack",
    "Do I have the record for the most hated mod?",
    "What language? .. English.",
    "Clarence plush when?",
    "The nether!",
    "Our Assets Are Bundle",
    "Function ADVR.onLoad() then...end", --rex is a silly Good news
    "I would never cry to a frank ocean song, lets be honest",
    "And we run And we run And we run And we run And we run And we run And we run And we run",
    "It is what it be, but what it do - Papa Nooter",
    "Also try deadly delivery",
    "job",
    "refrigerator doesn't have a d but fridge does - Kuiq",
    "Fuck mm - rex",
    "the simpler things have something special to them <3 - Tuzi",
    "The dungeon is woke all year round - ErThu",
    "You may worry about your hair-do today, but tomorrow much peanut butter will be sold.",
    "Try to value useful qualities in one who loves you.",
    "Giggity",
    "People 'round here...They call me..The Villain",
    "Also try POIs Galore",
    "Shut your skin tone chicken bone google chrome no home flip phone disowned ice cream cone garden gnome extra chromosome metronome dimmadome genome full blown monochrome student loan Indiana Jones overgrown flintstone x and y hormone friendzone Sylvester Stallone Sierra Leone autozone professionally seen silver patrone ching Chong lin long suck my ding dong headass remote control autism down syndrome stage four terminal brain cancer O'Riley autoparts silver bronze ash amino UV light pen sushi ram ramen Harisson Ford gamer bitch ass Virgin lamp thermometer lean mean string bean Charlie Sheen limousine canteen trampoline serpentine anti histamine wolverine submarine unclean nectarine broken gene Halloween detective spleen smoke screen James Dean putting green tiny peen anti vaccine aquamarine eugene extra green nicotine vaseline jelly bean magazine protein Lightning McQueen vending machine what'chu mean ocean man by ween head ass tf up bitch ",
    "*overgrown impressed*",
    "https://www.youtube.com/watch?v=E4WlUXrJgy4",
    "WE CAN BE THE GOOD GUYS OR WE CAN BE THE GUYS THAT SAVE THE WORLD.",
    "We're still on the same side, still trying to save lives, and we're still the good guys",
    "Fuck mm - Tennoji",
    "Did you know that the Flail also doubles as a MACE?!",
    "Sewer zombies are one shot when coming out of the water",
    "You can block arrow traps with your weapon",
    "I like trains",
    "A dungeon a day keeps the doctors away  - Jonathan",
    "RSNBAM",
    "Why is it spelled camouflage and not         ",
    "people who are intimate with the game. - FartExploder69",
    "You..Don't..Have..to..be..the.bad.guy",
    "I have no personality and I must larp",
    "Also try the vanilla game",
    "fouroboros is goated but people use it once, don't like it, and refuse to try it again - Sgt.Sillypants",
    "I swear that pot moved just now",
    "Don't instantly leave if things aren't going your way :3 - Shell",
    "Who is this bad bunny I keep hearing about, the only bad bunny I know of is judy hopps",
    "Also never try gorilla tag",
    "Protein tubes with that white sauce",
    "This is good news, we can finally be bees",
    "It may or may not be worthwhile, but it still has to be done.",
    "Beware of a tall blond man with one black shoe.",
    "Clock strikes 12...",
    "Your business will go through a period of considerable expansion.",
    "To win, you must first learn how you lost - deathly4",
    "I love luminous depths - luminous depths glazer",
    "you miss 100% of the shots you dont take - JmanWhitt",
    "I exist - DrFlameK21",
    "can we keep discussion out of this channel - Kuiq",
    "I am in a very chinese part of my life",
    "holy shit my flail bomb became a magic airstrike - Glitchking",
    "I'm gonna put you on a fucking rack - FartExploder69",
    "Im not gonna sugar coat it",
    "Don't even trip dawg",
    "Don't even sugarcoat it dawg",
    "Cornball - beanhawk.",
    "auaghghugh - debbie",
    "Im with you in the dark splash text - John Floors",
    "Are we still doing that whole CMR thing?",
    "'Always without desire we must be found, If its deep mystery we would sound; But if desire always within us be, Its outer fringe is all that we shall see.' - Dao De Jing first chapter'' - Rafi",
    "Bait or low IQ, call it",
    "You can fling yourself on climbable objects",
    "ErThu, go to bed",
    "woman stand, woman go, man stand, mango",
    "Life, is roblox",
    "Have you tried pickle pepsi, its awful",
    "Jonathan, you never had that h in your name I swear",
    "I wish I could do emojis in these",
    "Have you ever had a dream",
    "Who is he?!",
    "Merry Christmas",
    "[title card]",
    "'When do tester apps open'",
    "dih",
    "I came, I saw, I conquered",
    "or shall I say I saw, I conquered, I came",
    "sumalumadumayouassuminimahumanwhatigottadotogetitthroughtoyouimsuperhumaninnovativeandimmadeofrubbersowhateveryousayisricocheingoffanditllgluetoyouandimdevastatingmorethaneverdemonstratinghowtogiveamotherfuckingaudienceafeelinglikeitslevitatingneverfadingandIknowthehatersareforeverwaitingforthedaythattheycansayIfellofftheyllbecelebratingcauseIknowthewaytogetemmotivatedImakeelevatingmusicyoumakeelevatormusic",
    "Your motives for doing whatever good deed you may have in mind will bemisinterpreted by somebody.",
    "Is that really YOU that is reading this?",
    "You are always busy",
    "Beware of Bigfoot!",
    "You will be awarded the Nobel Peace Prize... posthumously.",
    "Can we get much higher",
    "Excellent time to become a missing person.",
    "El Cinco stays en La casa",
    "Tomorrow will be cancelled due to lack of interest.",
    "You will obey or molten silver will be poured into your ears.",
    "Q: What's hard going in and soft and sticky coming out?  A: Chewing gum. ",
    "You will be a winner today.  Pick a fight with a four-year-old.",
    "Are you sure the back door is locked?",
    "did you leave the oven on?",
    "You will pay for your sins.  If you have already paid, please disregard this message.",
    "You're a card which will have to be dealt with.",
    "Always bet on black",
    "How do you keep a moron in suspense?",
    "Stand ready for my arrival worm",
    "You will contract a rare disease.",
    "You have a will that can be influenced by all with whom you come in contact.",
    "Your lucky color has faded.",
    "Do what comes naturally.  Seethe and fume and throw a tantrum.",
    "So there was this lobster right - Oliver",
    "Every day I shit on m phone",
    "fart tickle nugget on a stick - Sgt. Sillypants",
    "Leave the game",
    "I think I see something hanging there",
    "OuuueeeeaaAaaooouuuu",
    "Still water, those who know",
    "Triple T",
    "Rest In Peace my granny",
    "Kaboom..Kablow",
    "MIMEN!!",
    "When you've recovered and secured your account send me a DM and I'll remove your timeout. - Kuiq 24/7",
    ":]",
    "sudo rm -rf /",
    "The torture chamber",
    "Music Based Weapon!!!!!!!!!!!!",
    "Does it work on mindflayer? - rex",
    "I caught a pokemon, Batman",
    "There's no laws against the pokemon Batman",
    "I think a Spear and Shie--",
    "Good day to let down old friends who need help.",
    "An avocado-tone refrigerator would look good on your resume.",
    "Don't you wish you had more energy... or less ambition?",
    "A tall, dark stranger will have more fun than you.",
    "Excellent day for putting Slinkies on an escalator.",
    "After your lover has gone you will still have PEANUT BUTTER!",
    "You will live to see your grandchildren.",
    "You have Egyptian flu: you're going to be a mummy.",
    "Tis but a scratch",
    "Have you drank water today?",
    "Round 1, FIGHT",
    "I made a Steak", -- A STEAK!?
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "Ya like jazz?",
}
function SplashText()
    local quote = Quotes[math.random(#Quotes)]
    game.ShowMessageInWorld(quote, Sec)
end
